apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-creds
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: azure-creds
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: capz-manager-bootstrap-credentials
